#!/bin/bash

set -euo pipefail

if [ -z "${1:-}" ]; then
  for day in "day*.py"; do
    echo $day
    python3.7 $day | while read line
      do printf "    %s\n" "$line"
    done
  done
else
  python3.7 "$1"
fi
