from day08 import *

EXAMPLE_1 = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

EXAMPLE_2 = """
..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
"""

EXAMPLE_3 = """
T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........
"""


def test_parse_input():
    size, grid = parse_input(EXAMPLE_1)
    assert len(grid["A"]) == 3
    assert Point(9, 2) in grid["A"]


def test_find_antinodes():
    size, grid = parse_input(EXAMPLE_2)
    antinodes = find_antinodes(size, grid["a"])
    assert set(antinodes) == {Point(6, 2), Point(3, 8)}


def test_find_antinodes_2():
    size, grid = parse_input(EXAMPLE_3)
    assert len(find_antinodes(size, grid["T"])) == 9


def test_part_1():
    assert part_1(EXAMPLE_1) == 14
